language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet test ./RtspClientSharp.UnitTests -c Release -f netcoreapp2.0
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
